// Kings Pride Infra — Project Intelligence Database
// Auto-curated from official brochures (Google Drive) + uploaded 4K renders.

const driveImg = (id, w = 1600) => `https://lh3.googleusercontent.com/d/${id}=w${w}`
const driveFile = (id) => `https://drive.google.com/file/d/${id}/view`

// User-uploaded high-resolution 4K hero renders
export const HERO_RENDERS = {
  goldenPalmTower: 'https://customer-assets.emergentagent.com/job_luxury-realty-hub-27/artifacts/kpylqki0_img2.png',
  goldenPalmEntrance: 'https://customer-assets.emergentagent.com/job_luxury-realty-hub-27/artifacts/aayijg1o_project2.png',
  goldenPalmGate: 'https://customer-assets.emergentagent.com/job_luxury-realty-hub-27/artifacts/mi427mei_project3.png',
  vantageFarms: 'https://customer-assets.emergentagent.com/job_luxury-realty-hub-27/artifacts/v596vhzx_project4.png',
  chandanValley: 'https://customer-assets.emergentagent.com/job_luxury-realty-hub-27/artifacts/elsu4vuo_IMG1.png',
  doctorsColony: 'https://customer-assets.emergentagent.com/job_luxury-realty-hub-27/artifacts/jqa7x8uz_project_1.png',
}

export const BRAND = {
  legalName: 'K.P. Infra Projects Pvt. Ltd.',
  displayName: 'Kings Pride Infra',
  shortName: 'KP Infra',
  tagline: 'A Bridge To Your Dream Home',
  subTagline: 'Discover the next chapter of Luxury Living',
  established: 2003,
  yearsOfLegacy: new Date().getFullYear() - 2003,
  website: 'www.kpinfraprojects.com',
  phone: '040-23522339',
  phoneIntl: '+91 40 2352 2339',
  mobile1: '+91 79977 00031',
  mobile2: '+91 79977 00032',
  email: 'sales@kpinfraprojects.com',
  office: {
    line1: '12-2-709/C/221, 1st Floor, Saleem Manzil',
    line2: 'Reti Bowli, P.V.N.R. Expressway, Opp. Pillar No.56',
    area: 'Mehdipatnam',
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500028',
  },
  whatsapp: '917997700031',
}

export const STATS = {
  yearsOfLegacy: 22,
  happyFamilies: 12000,
  projectsDelivered: 10,
  acresDeveloped: 250,
}

export const PROJECTS = [
  // ============ FLAGSHIP — Golden Palm City ============
  {
    id: 'golden-palm-city',
    name: 'Golden Palm City',
    isFlagship: true,
    category: 'Premium Layout',
    status: 'Ongoing',
    type: 'Residential & Commercial Plotted Community',
    tagline: 'A Destination for High Class Living',
    location: 'Macharam, Jadcherla, Telangana',
    distance: '200 m from NH-44 • 5 min to Jadcherla IT Park',
    price: 'On Request',
    priceLabel: 'Premium Investment',
    plotRange: '161 – 2,950 sq.yds',
    totalArea: '7 Acres 27 Guntas (37,147 sq.yds)',
    totalAreaShort: '7.27 Acres',
    possession: 'Under Development',
    approval: 'DTCP • MUDA • RERA',
    rera: 'LP No. 0032/GP/SWDL/2026',
    image: HERO_RENDERS.goldenPalmTower,
    gallery: [
      HERO_RENDERS.goldenPalmTower,
      HERO_RENDERS.goldenPalmEntrance,
      HERO_RENDERS.goldenPalmGate,
      // Real architectural renders from Drive (ARCH folder)
      driveImg('1jaI36PczWpY0IOZ9tt80rRlMmDgK4cSQ'),
      driveImg('1KUWGeTF_ZJ64C27zf89C6PY2OxLAB95H'),
      driveImg('1YE7YJ-okdTTmvoUEo4pr7xI7SeHaQdbL'),
      driveImg('1KTF6_LfPcNGTk0AD1mnqbUvttuucgFB-'),
      driveImg('1zTd4tmhu6fiWAVTgo3AB8vfk91h4FWuX'),
      // Park
      driveImg('1MKIxENaIGyECb1oQwJ2AxKvO-qLrumDH'),
      // Coffee shop
      driveImg('17Fq-f4kpe1H3Mw6JcsSRPyFHBc-XHAgm'),
      // Drone
      driveImg('10SoAzJUrtuRBKuyJZDlNz6HCXLqKjr9p'),
      driveImg('15k73jmPwvsna2yxYTtydmzzQZDwcEeSV'),
      // Building photo
      driveImg('1QcQb9BMhMeH9CGv1zzP4jzGsadxO5SW8'),
    ],
    brochureUrl: driveFile('1FQkhovKY-dvQjEAeSXd9p5ZEvvwEkADz'),
    layoutPdf: driveFile('1Z8oVXD75tIa90xPVwaRPfswW_M120nxp'),
    highlights: [
      'NH-44 Highway Facing',
      '100% Vaastu Compliant',
      'Clubhouse & Pool',
      'Sports Arena',
      'Food Court',
      'Studio Apartments',
      'Commercial Space',
    ],
    blocks: [
      { name: 'A', area: '2,829.99' },
      { name: 'B', area: '2,940.29' },
      { name: 'C', area: '2,317.38' },
      { name: 'D', area: '3,282.78' },
      { name: 'E', area: '3,282.78' },
      { name: 'F', area: '1,555.00' },
      { name: 'G', area: '1,547.34' },
      { name: 'H', area: '2,950.11' },
      { name: 'I', area: '2,308.51' },
    ],
    composition: {
      plotted: { pct: 59.32, label: 'Plotted Area', sqYds: '22,037' },
      roads: { pct: 28.13, label: 'Roads', sqYds: '10,450' },
      park: { pct: 10.00, label: 'Park', sqYds: '3,716' },
      social: { pct: 2.55, label: 'Social Infra', sqYds: '949' },
    },
    amenities: [
      'Elegant Entrance Arch', 'Clubhouse', 'Swimming Pool', 'Kids Play Area',
      'Sports Arena', 'Food Court', 'Verdant Park', 'Overhead Water Tank',
      'Underground Drainage', '40/33/30 ft Black-top Roads', 'Footpaths for 40\u2032 Roads',
      'Avenue Plantation', 'Rainwater Harvesting', 'Street Lights',
      '24x7 Gated Security', 'Pollution-Free Environment',
    ],
    nearby: [
      { name: 'Hyderabad – Bengaluru NH-44', dist: '200 m' },
      { name: 'Jadcherla Town', dist: '5 min' },
      { name: 'Jadcherla IT Park', dist: '5 min' },
      { name: 'Pollepally SEZ', dist: 'Adjacent' },
      { name: 'Symbiosis Intl. University', dist: 'Nearby' },
      { name: 'NMIMS', dist: 'Nearby' },
      { name: 'Rajiv Gandhi Intl. Airport', dist: 'On NH-44' },
      { name: 'Statue of Equality', dist: 'Drive' },
    ],
    neighbours: [
      'Aurobindo Pharma', 'Mylan Labs', 'Hetero Bio Pharma',
      'Olectra Electric Buses', 'DSM Nutritional Products', 'Thermo Cables',
      'Supreme Industries', 'L&T Training Center',
    ],
    usps: [
      'Premium residential + commercial highway-facing project',
      '100% Clear Title, Vaastu-compliant layout',
      'Adjacent to Pollepally SEZ (1000+ acres of employment)',
      'Smart investment with un-parallel connectivity',
    ],
  },

  // ============ Ongoing — Vantage Farms (UPDATED with real ₹5K pricing) ============
  {
    id: 'vantage-farms',
    name: 'Vantage Farms',
    category: 'Farm Land',
    status: 'Ongoing',
    type: 'Premium Farm Land Plots',
    tagline: 'Your dream property awaits at an unbeatable price',
    location: 'Shadnagar, Rangareddyguda',
    distance: '1 km from Bangalore Highway • 40 km from Airport',
    price: '₹ 5,000 / sq.yd',
    priceLabel: 'Starting from',
    plotRange: '605 – 1,001 sq.yds',
    totalArea: 'Phase 1 (3 acres for expansion)',
    possession: 'Phase 1 Ready',
    approval: 'Non-Agriculture Approved',
    rera: 'MUDA (Phase 2)',
    image: HERO_RENDERS.vantageFarms,
    gallery: [
      HERO_RENDERS.vantageFarms,
      driveImg('1CtV6cZcuRVEJPIoDL1XCFOfa7TTjifjZ'),
      driveImg('18wzXklqD0BdiLUr52VtbDEy5CIKuLN3B'),
      driveImg('1FFCkBsRiX-OzorjHIZt60ZkzpvKR5XOL'),
      driveImg('1RucoKNr_wF5uo9DSZQ-20E6FZNr2QRhs'),
      driveImg('1eBTrgtv-2EsW8b-lX6oyTAyrvmcD6M_h'),
    ],
    brochureUrl: driveFile('1uRQgaNJDWCwjPxzdlzrXZK_Z1OZ1o8rb'),
    highlights: ['20+ Year Mango Trees', '24/7 CCTV Surveillance', 'Transformer & Street Lights', 'Pre-Cast Boundary', 'Non-Agriculture Approved'],
    amenities: ['24/7 CCTV Surveillance', 'Transformer & Street Lights', 'Overall Pre-cast Wall', 'Security Gate', '24/7 Borewater', 'Individual Road Access'],
    nearby: [
      { name: 'Bangalore Highway', dist: '1 km' },
      { name: 'Proposed RRR', dist: '10 min' },
      { name: 'Balanagar SEZ', dist: '10 min' },
      { name: 'Pollepally SEZ', dist: '15 min' },
      { name: 'Microsoft Data Centre', dist: '15 min' },
      { name: 'Symbiosis University', dist: '15 min' },
      { name: 'RGI Airport / ORR', dist: '40 km' },
      { name: 'Statue of Equality', dist: '45 min' },
    ],
    usps: ['Limited-time offer at unbeatable ₹5,000/sq.yd', 'Non-Agriculture approved farm plots', 'Tranquil weekend escape with full infrastructure'],
  },

  // ============ Ongoing — Chandan Valley (UPDATED with Shamshabad + HMDA+RERA) ============
  {
    id: 'chandan-valley',
    name: 'Chandan Valley',
    category: 'Farm Land',
    status: 'Ongoing',
    type: 'Premium Hill-View Farm Land',
    tagline: 'Your dream property awaits in nature\u2019s lap',
    location: 'Chandan Valley, Shamshabad, Hyderabad',
    distance: '20 min to ORR • Near 1600-acre Chandanvelly SEZ',
    price: 'On Request',
    plotRange: '1,210 – 1,702 sq.yds (10–14 guntas)',
    totalArea: '3 Acres',
    possession: 'Ready to Register',
    approval: 'RERA & HMDA Approved',
    rera: 'RERA Approved',
    image: HERO_RENDERS.chandanValley,
    gallery: [
      HERO_RENDERS.chandanValley,
    ],
    brochureUrl: driveFile('1DyRbO4QmxPt6RQ-SeHgzv7d8QbxvUcMF'),
    highlights: ['Scenic Hill Views', 'Eco-Friendly Living', '24/7 Security', 'Well-Connected Location', 'RERA & HMDA Approved'],
    amenities: ['Pre-cast Boundary Wall', 'Entrance Gate', 'Electric Poles with Transformer', 'Avenue Plantation', '25 ft Roads', 'Numbering Stones', '24/7 Security'],
    nearby: [
      { name: 'WELSPUN Flooring', dist: '5 min' },
      { name: 'Amazon Data Centre', dist: '5 min' },
      { name: 'Microsoft Data Centre', dist: '5 min' },
      { name: 'Vardhaman Engg College', dist: '15 min' },
      { name: 'Shamshabad / Chevella', dist: '15 min' },
      { name: 'ORR & RGI Airport', dist: '20 min' },
      { name: 'Chandanvelly SEZ (1600 acres)', dist: 'Adjacent' },
    ],
    usps: ['Hill-view farm retreat with RERA & HMDA approval', 'Adjacent to 1600-acre SEZ', 'Eco-friendly living in scenic nature'],
  },

  // ============ Ongoing — Doctor's Colony (UPDATED — REAL DATA from OCR) ============
  {
    id: 'doctors-colony',
    name: 'Doctor\u2019s Colony',
    category: 'DTCP',
    status: 'Ongoing',
    type: 'DTCP Approved Residential Layout',
    tagline: 'Your dream property awaits you',
    location: 'Balanagar, Shadnagar (Mahabubnagar Dist.)',
    distance: '2 min from Balanagar Rly Station • 20 min to Airport',
    price: 'On Request',
    plotRange: '183 – 329 sq.yds',
    totalArea: '38 Plots',
    possession: 'Spot Registration Available',
    approval: 'DTCP Approved',
    rera: 'DTCP No. 14/2022/DTCPO/MBNR',
    image: HERO_RENDERS.doctorsColony,
    gallery: [
      HERO_RENDERS.doctorsColony,
    ],
    brochureUrl: driveFile('1T0CTYaKXio0oNwYbg7y4NKTvtNJ3HV_D'),
    highlights: ['Modern Design', 'Green & Serene Environment', '24/7 Security', 'Well Connected Location', 'DTCP Approved'],
    amenities: [
      'Compound Wall', 'Entrance Gate with Arch', 'Electricity Connection',
      'Modern Street Lighting', 'Water Connection per Plot',
      'Full Underground Drainage', 'Curbing Stones', 'Avenue Plantation',
      'Well-Developed Footpaths', 'Park', '24 Hours Security',
      '33\u2032 Wide BT Roads', '100% Vaasthu Compliant',
    ],
    nearby: [
      { name: 'NH-44', dist: 'Very Close' },
      { name: 'Balanagar Rly Station', dist: '2 min' },
      { name: 'Regional Ring Road', dist: '2 km' },
      { name: 'NRSC', dist: '10 min' },
      { name: 'Amazon', dist: '10 min' },
      { name: 'P&G / J&J', dist: '10 min' },
      { name: 'NATCO / MSN Lab', dist: '10 min' },
      { name: 'Microsoft', dist: '10 min' },
      { name: 'Rajapur SEZ (TSIIC)', dist: '10 min' },
      { name: 'TATA Institute of Social Sciences', dist: '15 min' },
      { name: 'Statue of Equality', dist: '15 min' },
      { name: 'RGI Airport / ORR', dist: '20 min' },
    ],
    usps: [
      'DTCP approved layout with clear title — spot registration available',
      'Very close to NH-44 with 33\u2032 BT roads',
      '38 well-designed plots — 100% Vaastu compliant',
      'Surrounded by Amazon, P&G, J&J, NATCO, Microsoft — premier employment cluster',
    ],
  },

  // ============ Completed ============
  {
    id: 'adarsh-nagar',
    name: 'Adarsh Nagar',
    category: 'HMDA',
    status: 'Completed',
    type: 'Residential Township',
    tagline: 'Where established communities flourish',
    location: 'Hyderabad, Telangana',
    distance: 'Established neighbourhood',
    price: 'Resale Available',
    plotRange: 'Multiple sizes',
    totalArea: '—',
    possession: 'Handover Done',
    approval: 'HMDA',
    rera: '—',
    image: driveImg('1tgvmLjpd77ytwfkoSoQsxvl7kU_hJBS7'),
    gallery: [
      driveImg('1tgvmLjpd77ytwfkoSoQsxvl7kU_hJBS7'),
      driveImg('16kDMnbjLLBomZWArtti5eQs7uj74H6qW'),
      driveImg('1MBYYM4JpVPrt_wXDKSfw3MYeJzI7NR25'),
      driveImg('1VKFLFr7pN8c7P13MAO5mdNJry93sZ2_7'),
    ],
    highlights: ['Established 2009', 'Fully Occupied', 'Mature Neighbourhood'],
    amenities: ['Wide Roads', 'Street Lights', 'Park', 'Drainage', 'Water Connection'],
    nearby: [],
    usps: ['One of our earliest delivered townships — now a mature, thriving neighbourhood'],
  },
  {
    id: 'golden-spring',
    name: 'Golden Spring',
    category: 'HMDA',
    status: 'Completed',
    type: 'Residential Plotted Layout',
    tagline: 'A new dawn in plotted living',
    location: 'Hyderabad, Telangana',
    distance: 'Premium Hyderabad address',
    price: 'Resale Available',
    plotRange: 'Multiple sizes',
    totalArea: '—',
    possession: 'Handover Done',
    approval: 'HMDA',
    rera: '—',
    image: driveImg('15k73jmPwvsna2yxYTtydmzzQZDwcEeSV'),
    gallery: [],
    highlights: ['Resale Available', 'Approved Layout', 'Excellent Connectivity'],
    amenities: ['Compound Wall', 'Roads', 'Park', 'Street Lights'],
    nearby: [],
    usps: ['Part of our flagship "Golden" series of premium plotted communities'],
  },
  {
    id: 'golden-view',
    name: 'Golden View',
    category: 'HMDA',
    status: 'Completed',
    type: 'Residential Plotted Layout',
    tagline: 'Vistas that elevate everyday living',
    location: 'Hyderabad, Telangana',
    distance: 'Premium Hyderabad address',
    price: 'Resale Available',
    plotRange: 'Multiple sizes',
    totalArea: '—',
    possession: 'Handover Done',
    approval: 'HMDA',
    rera: '—',
    image: driveImg('15k73jmPwvsna2yxYTtydmzzQZDwcEeSV', 1200),
    gallery: [],
    highlights: ['Resale Available', 'Drone & Video Gallery', 'Approved Layout'],
    amenities: ['Compound Wall', 'Roads', 'Park', 'Street Lights'],
    nearby: [],
    usps: ['Curated for buyers who value uninterrupted views and prime placement'],
  },
  {
    id: 'lucky-farms',
    name: 'Lucky Farms',
    category: 'Farm Land',
    status: 'Completed',
    type: 'Farm Land',
    tagline: 'Your private piece of green',
    location: 'Telangana',
    distance: 'Weekend retreat zone',
    price: 'Resale Available',
    plotRange: 'Multiple sizes',
    totalArea: '—',
    possession: 'Handover Done',
    approval: 'Clear Title',
    rera: '—',
    image: driveImg('1RucoKNr_wF5uo9DSZQ-20E6FZNr2QRhs'),
    gallery: [],
    highlights: ['Mature Farm Plots', 'Brochure & Videos Available', 'Resale Available'],
    amenities: ['Boundary', 'Roads', 'Water', 'Plantation'],
    nearby: [],
    usps: ['One of our most beloved farm-land projects — a true weekend retreat'],
  },
  {
    id: 'moinabad-township',
    name: 'Moinabad Township',
    category: 'Township',
    status: 'Completed',
    type: 'Integrated Township',
    tagline: 'A complete township, a complete life',
    location: 'Moinabad, Telangana',
    distance: 'Established township',
    price: 'Resale Available',
    plotRange: 'Multiple sizes',
    totalArea: 'Largest delivered project',
    possession: 'Handover Done (2018)',
    approval: 'HMDA',
    rera: '—',
    image: driveImg('1kG9uy3Y0ce-2x7hikwecW8hFEzkofd9C'),
    gallery: [
      driveImg('1kG9uy3Y0ce-2x7hikwecW8hFEzkofd9C'),
      driveImg('1Aa9sHpQWLF8d70ogdnGhOjEZ9IjjOOCW'),
      driveImg('12nh36ZoxpFDD0fmhLiSsbKJ1OUs99lB9'),
      driveImg('11F32mGqIcvtB19EPbvV3Eoj2Pn4vH-rM'),
      driveImg('1hYvbxMAZgGgDUIWYrig10ZT41Ap1tBn_'),
    ],
    highlights: ['Delivered 2015–2018', 'Integrated Township', 'Mature Community'],
    amenities: ['Wide Roads', 'Park', 'Drainage', 'Water', 'Street Lights', 'Boundary'],
    nearby: [],
    usps: ['Our defining integrated-township delivery and proof of execution at scale'],
  },
  {
    id: 'royale-meadows',
    name: 'Royale Meadows',
    category: 'HMDA',
    status: 'Completed',
    type: 'Premium Plotted Layout',
    tagline: 'Royale living, meadow serenity',
    location: 'Telangana',
    distance: 'Premium address',
    price: 'Resale 2.3x',
    plotRange: 'Multiple sizes',
    totalArea: '—',
    possession: 'Handover Done',
    approval: 'HMDA',
    rera: '—',
    image: driveImg('18qJ-Bmv4WGCHJj3ya7UZehp_kSDNFjgs'),
    gallery: [
      driveImg('18qJ-Bmv4WGCHJj3ya7UZehp_kSDNFjgs'),
      driveImg('1YVPD-UEz8D0Z3tkeqbXqjQwkKzidW5ad'),
      driveImg('1x19lRQ0WUZqnfLGbSHYzvmAqbLIuAEik'),
      driveImg('15FT4t3GfsyXE0evC5cMSUNQszSQDXLH_'),
      driveImg('10TEiHqfK7CWq0s1EgGEv65a0cMHQz8fu'),
    ],
    highlights: ['Drone Footage Available', 'Strong Resale Value', 'Approved Layout'],
    amenities: ['Wide Roads', 'Park', 'Drainage', 'Water', 'Plantation'],
    nearby: [],
    usps: ['One of our top-performing plot investments by resale appreciation'],
  },
]

export const TIMELINE = [
  { year: '2003', title: 'Foundation', desc: 'K.P. Infra Projects established with a single layout in Hyderabad.' },
  { year: '2009', title: 'Adarsh Nagar Delivered', desc: 'Early residential township delivery establishing our reputation for clean execution.' },
  { year: '2015', title: 'Moinabad Township', desc: 'Began our flagship integrated township\u2014largest delivered asset to date.' },
  { year: '2018', title: 'Moinabad Handover', desc: 'Completed the Moinabad Township delivery, cementing scale-execution credibility.' },
  { year: '2019', title: '"Golden" Series Launch', desc: 'Premium plotted layouts: Golden Spring, Golden View — defining our luxury vertical.' },
  { year: '2022', title: 'Doctor\u2019s Colony', desc: 'DTCP-approved boutique layout in Balanagar (DTCP No. 14/2022/DTCPO/MBNR).' },
  { year: '2024', title: 'Vantage Farms', desc: 'Launched non-agriculture approved farm plots from \u20B95,000/sq.yd on the BLR-HYD corridor.' },
  { year: '2025', title: 'Chandan Valley', desc: 'RERA & HMDA approved hill-view farm land near the 1600-acre Chandanvelly SEZ.' },
  { year: '2026', title: 'Golden Palm City', desc: 'Our flagship NH-44 highway-facing residential + commercial city in Macharam, Jadcherla.' },
]

export const FILTERS = ['All', 'Flagship', 'Ongoing', 'Completed', 'Farm Land', 'HMDA', 'DTCP', 'Township']

export const TESTIMONIALS = [
  { name: 'Ravi Teja', role: 'NRI Investor, Dubai', rating: 5, quote: 'I invested in Golden Spring sight unseen — based purely on KP Infra\u2019s reputation. Five years later, my plot doubled. That\u2019s the kind of trust they\u2019ve built.' },
  { name: 'Sandhya Reddy', role: 'IT Professional, Hyderabad', rating: 5, quote: 'From the first site visit to registration at Moinabad Township, the KP team treated us like family. Clear titles, no hidden costs, on-time delivery.' },
  { name: 'Arjun Khanna', role: 'Entrepreneur, Bangalore', rating: 5, quote: 'Vantage Farms at \u20B95,000/sq.yd was the easiest investment decision of my year. Non-agriculture approval, full CCTV, and 1 km from Bangalore highway.' },
  { name: 'Dr. Meera Iyer', role: 'NRI, San Francisco', rating: 5, quote: 'Golden Palm City\u2019s NH-44 highway frontage and SEZ proximity makes it one of the smartest plays in Telangana right now. KP Infra is the gold standard.' },
]

export const BLOGS = [
  {
    title: 'Why Jadcherla & Macharam are Hyderabad\u2019s Next Investment Goldmines',
    tag: 'Market Insights', date: 'Jun 2025', read: '6 min',
    excerpt: 'NH-44, Pollepally SEZ, and the upcoming RRR are converging in Jadcherla. Here\u2019s why Golden Palm City sits at the centre of it.',
    img: HERO_RENDERS.goldenPalmTower,
  },
  {
    title: 'The Chandanvelly SEZ Story — 1600 Acres Reshaping Rangareddy',
    tag: 'Investment', date: 'May 2025', read: '8 min',
    excerpt: 'How Microsoft, Amazon, and Welspun are turning Chandanvelly into a data-and-manufacturing super-cluster.',
    img: HERO_RENDERS.chandanValley,
  },
  {
    title: 'Why Farm Land at \u20B95,000/sq.yd is the Smartest Bet of 2026',
    tag: 'Guide', date: 'May 2025', read: '5 min',
    excerpt: 'Vantage Farms shows how non-agriculture approved farm plots blend lifestyle, returns and security.',
    img: HERO_RENDERS.vantageFarms,
  },
]
